# Generated by Django 3.2.3 on 2021-06-27 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresttoken',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 11, 17, 27, 268315)),
        ),
        migrations.AlterField(
            model_name='passwordresttoken',
            name='expaire_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 11, 17, 27, 268347)),
        ),
    ]
